Ingested Gspread Data Into Postgres Database and Utitlized Dbeaver to write SQL Scripts
Data-Epic/Ghost_Warriors pull request #4
Opened 2023-11-25 00:09 UTC by Humphery7

@elseagle 
@tobaadesugba 
@AmazingGrace-D 

-> Created Postgres Database
-> Utilized gspread library to get data from google spreadsheet  
-> Utilized psycopg2 library to send sql queries to database to perform actions(create_table, truncate_table, insert_into_table...)
-> Installed Dbeaver and connection setup to write sql scripts to database
-> Managed Packages with poetry
-> Validated Incoming data
-> logged errors encounted with logging library

2023-11-25 14:37 UTC, elseagle requested changes
Good work. Thank you.

I noticed you only have 1 PR, the instruction says otherwise. Kindly ensure you give more attention to details in these scenarios. All details matter.
<img width="847" alt="Screenshot 2023-11-25 at 15 36 10" src="https://github.com/Data-Epic/Ghost_Warriors/assets/27138575/34c6bcd2-b788-47f1-a896-c1946fa0a65c">

Kindly attend to requested changes too

2023-11-25 14:37 UTC, elseagle commented on Project5/project5/app.py
> +            print(f"Skipping row due to error: {e}")
Do not use print, use the logging library

2023-11-25 14:37 UTC, elseagle commented on Project5/project5/app.py
> +        print("Data inserted successfully")
Kindly remove all prints and use logging if needed

2023-11-25 14:37 UTC, elseagle commented on Project5/project5/app.py
> +            with open('Project5/project5/insert_values.sql', 'r') as file:
This belongs to .env

2023-11-25 14:37 UTC, elseagle commented on Project5/project5/config.py
> +def config(filename='Project5/project5/database.ini', section='postgresql'):
Magic string here should be an environment variable

2023-11-25 14:37 UTC, elseagle commented on Project5/project5/create_table.sql
> +    temp_c INT NOT NULL,
What's temp_c? Not quite descriptive

2023-11-25 14:37 UTC, elseagle commented on Project5/pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Your names should be here ¯\_(ツ)_/¯

2023-11-25 14:37 UTC, elseagle commented on Project5_II/python_sql.py
> +    with psycopg2.connect(host="localhost",dbname="GspreadData_Storage",
Your db name needs to look better. You can stick with lower case and use a descriptive name - `gspreaddata_storage` doesn't sound good. You should name your db based on the data, use case or task (I mean what is being achieved)

2023-11-25 14:37 UTC, elseagle commented on Project5_II/python_sql.py
> +                ID SERIAL NOT NULL,
Not a good naming, stick to lower case

2023-11-25 14:37 UTC, elseagle commented on Project5_II/python_sql.py
> +                Datetime_Posted VARCHAR(50) NOT NULL,
`created_at` sounds better.

2023-11-26 19:18 UTC, Humphery7 reviewed
@elseagle 
@tobaadesugba 

-> created better names for database and table 
-> names are ensured to be lower case
-> created entry point, script now runs on command (poetry run app)

2023-11-27 19:57 UTC, elseagle commented on Project5/project5/create_table.sql
> +    temp_c INT NOT NULL,
This is yet to be resolved @Humphery7 @LogicAL007

2023-11-27 22:21 UTC, elseagle approved these changes

2023-12-07 20:06 UTC, merged